# Generated by Django 4.0.4 on 2022-05-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_alter_classroom_instructors_alter_classroom_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Semester')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(max_length=36, null=True, verbose_name='Invitation Code'),
        ),
    ]
