# Generated by Django 4.0.4 on 2022-05-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_semester_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='evaluator.semester', verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
