# Generated by Django 4.0.4 on 2022-05-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_classroom_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Current Semester'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='evaluator.semester', verbose_name='Semester'),
        ),
    ]
