# Generated by Django 4.0.4 on 2022-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_semester_is_current_alter_classroom_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-is_current', '-created']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(editable=False, max_length=7, verbose_name='Invitation Code'),
        ),
    ]
