# Generated by Django 4.0.4 on 2022-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='Invitation Code'),
        ),
    ]
