# Generated by Django 4.0.4 on 2022-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_alter_classroom_invitation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='invitation_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='semester',
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='submmissions', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_distinct',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.JSONField(default={}, verbose_name='Result Data'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=500, null=True, verbose_name='Score'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
