# Generated by Django 4.0.4 on 2022-05-28 05:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluator', '0008_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'assignment')},
        ),
    ]
