# Generated by Django 4.0.4 on 2022-05-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0009_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Semester')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current Semester')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'ordering': ['is_current', '-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(max_length=36, null=True, verbose_name='Invitation Code'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='evaluator.semester', verbose_name='Semester'),
        ),
    ]
