# Generated by Django 4.0.4 on 2022-05-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0010_semester_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-is_current', '-created']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='evaluator.semester', verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
