# Generated by Django 4.0.4 on 2022-05-28 07:05

import ckeditor_uploader.fields
from django.db import migrations, models
import evaluator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0011_alter_semester_options_alter_classroom_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(upload_to=evaluator.utils.FilenameChanger('assignments'), verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(max_length=7, null=True, verbose_name='Invitation Code'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=evaluator.utils.FilenameChanger('submissions'), verbose_name='File'),
        ),
    ]
