# Generated by Django 4.0.4 on 2022-05-28 08:21

from django.db import migrations, models
import evaluator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0012_alter_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='data',
        ),
        migrations.AddField(
            model_name='criterion',
            name='config_file',
            field=models.FileField(null=True, upload_to=evaluator.utils.FilenameChanger('configurations'), verbose_name='Configuration File'),
        ),
    ]
