# Generated by Django 4.0.4 on 2022-05-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0014_assignment_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='name',
            field=models.CharField(default='Default', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
