# Generated by Django 4.0.4 on 2022-05-28 08:32

from django.db import migrations, models
import evaluator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0015_criterion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer_code',
            field=models.FileField(default='', upload_to=evaluator.utils.FilenameChanger('answer_codes'), verbose_name='Answer Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=evaluator.utils.FilenameChanger('assignments'), verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test_case',
            field=models.FileField(blank=True, null=True, upload_to=evaluator.utils.FilenameChanger('test_cases'), verbose_name='Test Case'),
        ),
    ]
