# Generated by Django 4.0.4 on 2022-05-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0017_alter_assignment_answer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='evaluator.assignment', verbose_name='Assignment'),
        ),
    ]
